#ifndef MEMOTOTHEMEDEFINITION_H
#define MEMOTOTHEMEDEFINITION_H

#include <QColor>

static const QColor SCENES_BACKGROUND_COLOR(220U, 220U, 220U);
static const QColor TEXT_GRAPHICS_COLOR(0U, 0U, 0U);

#endif // MEMOTOTHEMEDEFINITION_H
