name: Linux x86_64 build

on:
  push:
    branches:
      - main

jobs:
  build_memoto_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Registry
        uses : docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/memoto-builder/mmt \
            -it ghcr.io/raphaelmartin83/qt_compilation

