name: Linux x86_64 build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:

  build_memoto_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker run --rm \
            -e OUTPUT_DIR=/var/mmt/ \
            -e MMT_VERSION_MAJOR=1 \
            -e MMT_VERSION_MINOR=2 \
            -e MMT_VERSION_PATCH=3 \
            -v ${{ github.workspace }}:/var/mmt:rw \
            ghcr.io/raphaelmartin83/memoto_linux_x86_64:8485f18

      - name: Persist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MeMoTo-Linux-x86_64.AppImage
          path: ${{ github.workspace }}/MeMoTo-x86_64.AppImage

  deploy_memoto_linux_x86_64:
    needs: [build_memoto_linux_x86_64]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve artifacts to release
        uses: actions/download-artifact@v4
        with:
          name: MeMoTo-Linux-x86_64.AppImage
          path: ${{ github.workspace }}/MeMoTo-x86_64.AppImage

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/MeMoTo-x86_64.AppImage
          asset_name: Linux_x86_64_AppImage
          tag: ${{ github.ref_name }}
          overwrite: true
          body: "MeMoTo release ${{ github.ref_name }}"
