name: Linux x86_64 build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build_memoto_linux_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/home/memoto-builder/mmt \
            ghcr.io/raphaelmartin83/memoto_linux_x86_64

