name: MacOSX build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:

  build_memoto_macosx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker run --rm \
            -e OUTPUT_DIR=/var/mmt/ \
            -v ${{ github.workspace }}:/var/mmt:rw \
            ghcr.io/raphaelmartin83/memoto_macosx:4132415

      - name: Persist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: MeMoTo-MacOSX.dmg
          path: ${{ github.workspace }}/MeMoTo-MacOSX.dmg

  deploy_memoto_macosx:
    needs: [build_memoto_macosx]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Retrieve artifacts to release
        uses: actions/download-artifact@v4
        with:
          name: MeMoTo-MacOSX.dmg
          path: ${{ github.workspace }}

      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            sudo apt update
            sudo apt install fuse
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage ${{ github.workspace }}/MeMoTo-MacOSX.dmg
