name: MacOSX build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    tags:
      - 'v*'

jobs:

  build_memoto_macosx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker run --rm \
            -e OUTPUT_DIR=/var/mmt/ \
            -v ${{ github.workspace }}:/var/mmt:rw \
            ghcr.io/raphaelmartin83/memoto_macosx:4132415

